name: optimal
channels:
  - pytorch
  - defaults
dependencies:
  - pip=20.3.3
  - python=3.7.9
  - pytorch=1.7.1
  - torchvision=0.8.2
  - pip:
    - imageio==2.9.0
    - matplotlib==3.3.4
    - numpy==1.19.5
    - pygame==2.0.1
    - tqdm==4.58.0
